name: Test and publish release

on:
  release:
    types: [created]

jobs:
  test:
    name: Test and Publish Release
    runs-on: ubuntu-latest
    steps:
    - name: Cache pip
      uses: actions/cache@v2
      env:
        cache-name: cache-python-deps
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-${{ env.cache-name }}-release-3.9
        restore-keys: |
          ${{ runner.os }}-${{ env.cache-name }}-release-3.9
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install wheel
      run: |
        python -m pip install --upgrade pip wheel
    - name: Install dependencies
      run: |
        pip install flake8 pytest pysam coveralls setuptools
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --show-source --statistics
    - name: Run tests
      run: |
        coverage run --source=bellerophon -m pytest --junit-xml=junit_test_results.xml
    - name: Build source tarball and wheel
      run: |
        python setup.py sdist bdist_wheel
    - name: Publish release to Test-PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.TESTPYPI_API_KEY }}
        repository_url: https://test.pypi.org/legacy/
    - name: Publish release to PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.PYPI_API_KEY }}
        repository_url: https://pypi.org/legacy/
    - name: 'Upload jUnit Test Results'
      uses: actions/upload-artifact@v2
      with:
        name: jUnit Test Results
        path: junit_test_results.xml
      if: ${{ always() }}