name: Run nose tests

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6,3.7,3.8,3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest pytest-cov cpp-coveralls
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --show-source --statistics
    - name: Test with pytest
      run: |
        pytest --cov=bellerophon --junit-xml=junit_test_results_${{ matrix.python-version }}.xml --cov-report=coverage_${{ matrix.python-version }}.xml
    - name: 'Test Coverage Report: Python ${{ matrix.python-version }}'
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
    - name: 'jUnit Test Results: Python ${{ matrix.python-version }}'
      uses: actions/upload-artifact@v2
      with:
        name: jUnit Test Results
        path: junit_test_results_${{ matrix.python-version }}.xml
      if: ${{ always() }}